name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3
    
    - name: Generate Environment Variables File for Production
      run: |
        cd nexpotproject
        echo "MY_SECRET_KEY=${{ secrets.MY_SECRET_KEY }}">>my_settings.py
        echo "MY_DATABASES=${{ secrets.MY_DATABASES }}">>my_settings.py
        cat my_settings.py
        ls -al
        cd ..
        ls -al
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: oduodg/nexpot-backend:${{ github.sha }}
